### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Darik2121** [pankoza-pl/Thallium.exe#15]
Colmare is not skidded and working

**Comment by pankoza-pl** [comment]
Skidded not working g3tr3kt

**Comment by Darik2121** [comment]
> Skidded not working g3tr3kt

no skid and working no you get rekt

**Comment by Darik2121** [comment]
@pankoza-pl i had enough, one more saying "colmare skidded and not working" and i will unsub

**Comment by Darik2121** [comment]
done unsubbed

**Comment by pankoza-pl** [comment]
G3tr3kt

**Comment by G9-dev-real** [comment]
NO
