### ISSUE TITLE
SHUT UR MOUTH

### ISSUE THREAD

**Issue by Darik8Hacker** [pankoza-pl/Thallium.exe#8]
NOT BEST

**Comment by Nestor5Cat** [comment]
![DWANW-UnbannedFor3Days](https://user-images.githubusercontent.com/108619530/178150940-86b60031-a0de-4e38-812c-36fdb3426311.png)
User Darik8Hacker has been unbanned

**Comment by Darik8Hacker** [comment]
xd

**Comment by Nestor5Cat** [comment]
![DWANW-fe-skin-DWANWPope](https://user-images.githubusercontent.com/108619530/178151027-428d166f-6c57-4f2c-a15f-0655209bce08.png)
Darik world and Nestor world FE Skin (Fifth Skin 5)

**Comment by Nestor5Cat** [comment]
I WILL BAN THEHEN >:)
